site_name: ikun爱学习

theme:
  name: material  # 核心配置：使用 Material 主题
  palette: #调色板
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  
  language: zh #表示在浏览器中显示当前页面的语言是什么，如果是en，那么像谷歌浏览器就可以翻译

  font:
    text: "Noto Sans, Noto Sans SC"  # 优先使用Noto Sans显示符号
    code: "Fira Code, monospace"     # 添加monospace作为回退
  
  features:
    - navigation.instant     # 提供侧边栏开关
    - navigation.tabs        # 更好地组织导航
    - toc.integrate          # 提供 TOC 开关
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - search.highlight

plugins:
  - search

# ---------------------配置数学公式相关内容--------------------------
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - assets/javascripts/focus-mode.js

extra_css:
  - stylesheets/extra.css
# ---------------------end--------------------------
