site_name: ikun爱学习
theme:
  name: 
    material  # 核心配置：使用 Material 主题
  palette: #调色板
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  
  language:
    zh #表示在浏览器中显示当前页面的语言是什么，如果是en，那么像谷歌浏览器就可以翻译

  font:
    text: Roboto     # 正文字体
    code: Fira Code  # 代码字体
  
  features:
    - navigation.tabs       # 启用顶部标签页
    - navigation.indexes    # 显示章节索引

# ---------------------配置数学公式相关内容--------------------------
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
# ---------------------end--------------------------
