name: Deploy to GitHub Pages
on:
  push:
    branches: [ "mkdocs-new-theme" ]  # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 第一步：拉取代码

      - name: Build with MkDocs    # 第二步：构建（示例）
        run: |
          pip install mkdocs
          mkdocs build --site-dir ./site

      - name: Deploy to GitHub Pages  # 第三步：部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
