name: Deploy to GitHub Pages
on:
  push:
    branches: [ "mkdocs-new-theme" ]  # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs

      - name: Build with MkDocs
        run: mkdocs build --site-dir ./site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
